version: '3'

services:
  app:
    build: .
    ports:
      - "3002:3002"
    depends_on:
      - database

  database:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "file:../../../db.development.sqlite"
    volumes:
      - ./prisma:/app/src/infrastructure/database
      - ./migrations:/app/src/infrastructure/database/migrations
